# Generated by Django 3.1.6 on 2021-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirpotLoungeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Delhi AirPort Lounge', max_length=256)),
                ('price', models.CharField(default=5000, max_length=256)),
                ('size', models.CharField(default=12, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lounge Data',
                'verbose_name_plural': 'LG Lounge Access',
                'db_table': 'tbl_Lounge1',
                'ordering': ('-created_at',),
            },
        ),
    ]
